spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///mytestdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 2
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    #连接到 redis 的那个槽,默认是0，共有16个
    database: 0
    pool:
    #连接池最大连接数（使用负数，表示没有限制）
      max-active: 8
      #连接池最大阻塞时间，负数没有限制
      max-wait: -1
      #连接池中最大的空闲连接数
      max-idle: 8
      #最小空闲连接数
      min-idle: 0
  jpa:
    show-sql: true
#    open-in-view: true 默认就是true